// Prisma Seed Script - Import Album Items
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const albumItems = [
  {
    name: "Trạng Tí",
    category: "character",
    image: "🧒",
    price: 20,
    description: "Nhân vật Trạng Tí thông minh",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Thằng Bờm",
    category: "character",
    image: "👦",
    price: 20,
    description: "Nhân vật Thằng Bờm vui vẻ",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Chị Hằng",
    category: "character",
    image: "👧",
    price: 25,
    description: "Nhân vật Chị Hằng xinh đẹp",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Anh Cuội",
    category: "character",
    image: "👨",
    price: 25,
    description: "Nhân vật Anh Cuội trên cung trăng",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Bà Ngoại",
    category: "character",
    image: "👵",
    price: 30,
    description: "Bà Ngoại hiền từ",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Ông Ngoại",
    category: "character",
    image: "👴",
    price: 30,
    description: "Ông Ngoại thông thái",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Cô Giáo",
    category: "character",
    image: "👩‍🏫",
    price: 25,
    description: "Cô giáo dạy học",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Bác Sĩ",
    category: "character",
    image: "👨‍⚕️",
    price: 25,
    description: "Bác sĩ chữa bệnh",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Bạn Thân",
    category: "character",
    image: "👫",
    price: 22,
    description: "Đôi bạn thân",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Anh Trai",
    category: "character",
    image: "👨‍🦱",
    price: 23,
    description: "Anh trai lớn",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Chị Gái",
    category: "character",
    image: "👩",
    price: 23,
    description: "Chị gái xinh",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Em Bé",
    category: "character",
    image: "👶",
    price: 20,
    description: "Em bé dễ thương",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Bạn Học",
    category: "character",
    image: "🧑‍🎓",
    price: 22,
    description: "Bạn học cùng lớp",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Cô Bán Hàng",
    category: "character",
    image: "👩‍💼",
    price: 24,
    description: "Cô bán hàng rong",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Chú Công Nhân",
    category: "character",
    image: "👷",
    price: 24,
    description: "Chú công nhân chăm chỉ",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Bác Nông Dân",
    category: "character",
    image: "🧑‍🌾",
    price: 26,
    description: "Bác nông dân trồng lúa",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Cô Y Tá",
    category: "character",
    image: "👩‍⚕️",
    price: 25,
    description: "Cô y tá chăm sóc",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Chú Cảnh Sát",
    category: "character",
    image: "👮",
    price: 27,
    description: "Chú cảnh sát bảo vệ",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Bạn Nhỏ",
    category: "character",
    image: "🧒",
    price: 21,
    description: "Bạn nhỏ vui vẻ",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Thầy Giáo",
    category: "character",
    image: "👨‍🏫",
    price: 28,
    description: "Thầy giáo dạy học",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: false,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Nón Lá",
    category: "accessory",
    image: "👒",
    price: 15,
    description: "Nón lá Việt Nam",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Quạt Mo",
    category: "accessory",
    image: "🍃",
    price: 15,
    description: "Quạt mo cọ",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khăn Rằn",
    category: "accessory",
    image: "🧣",
    price: 20,
    description: "Khăn rằn Nam Bộ",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Áo Dài",
    category: "accessory",
    image: "👗",
    price: 25,
    description: "Áo dài truyền thống",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Nón Cối",
    category: "accessory",
    image: "🪖",
    price: 18,
    description: "Nón cối bảo vệ",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Kính Mát",
    category: "accessory",
    image: "🕶️",
    price: 16,
    description: "Kính mát thời trang",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Túi Xách",
    category: "accessory",
    image: "👜",
    price: 20,
    description: "Túi xách đẹp",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Vòng Cổ",
    category: "accessory",
    image: "📿",
    price: 17,
    description: "Vòng cổ trang sức",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Vòng Tay",
    category: "accessory",
    image: "📿",
    price: 16,
    description: "Vòng tay đẹp",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Cặp Sách",
    category: "accessory",
    image: "🎒",
    price: 22,
    description: "Cặp sách học sinh",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Mũ Lưỡi Trai",
    category: "accessory",
    image: "🧢",
    price: 15,
    description: "Mũ lưỡi trai",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khăn Quàng",
    category: "accessory",
    image: "🧣",
    price: 18,
    description: "Khăn quàng đỏ",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Giày Dép",
    category: "accessory",
    image: "👟",
    price: 19,
    description: "Giày dép đi học",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Ô Dù",
    category: "accessory",
    image: "☂️",
    price: 17,
    description: "Ô dù che mưa",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Balo",
    category: "accessory",
    image: "🎒",
    price: 21,
    description: "Balo đi học",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Mũ Bảo Hiểm",
    category: "accessory",
    image: "⛑️",
    price: 23,
    description: "Mũ bảo hiểm an toàn",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Găng Tay",
    category: "accessory",
    image: "🧤",
    price: 16,
    description: "Găng tay ấm",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Tất Chân",
    category: "accessory",
    image: "🧦",
    price: 14,
    description: "Tất chân ấm",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Kính Đeo Mắt",
    category: "accessory",
    image: "👓",
    price: 18,
    description: "Kính đeo mắt",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Đồng Hồ",
    category: "accessory",
    image: "⌚",
    price: 24,
    description: "Đồng hồ xem giờ",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Cửa Sổ",
    category: "frame",
    image: "🖼️",
    price: 10,
    description: "Khung cửa sổ đẹp",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Làng Quê",
    category: "frame",
    image: "🏞️",
    price: 15,
    description: "Khung cảnh làng quê",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Phố Cổ",
    category: "frame",
    image: "🏛️",
    price: 20,
    description: "Khung cảnh phố cổ",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Biển",
    category: "frame",
    image: "🌊",
    price: 18,
    description: "Khung cảnh biển",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Núi",
    category: "frame",
    image: "⛰️",
    price: 17,
    description: "Khung cảnh núi",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Đồng Lúa",
    category: "frame",
    image: "🌾",
    price: 16,
    description: "Khung cảnh đồng lúa",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Cầu",
    category: "frame",
    image: "🌉",
    price: 19,
    description: "Khung cảnh cầu",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Chùa",
    category: "frame",
    image: "⛩️",
    price: 20,
    description: "Khung cảnh chùa",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Nhà",
    category: "frame",
    image: "🏠",
    price: 12,
    description: "Khung cảnh nhà",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Trường Học",
    category: "frame",
    image: "🏫",
    price: 14,
    description: "Khung cảnh trường học",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Công Viên",
    category: "frame",
    image: "🌳",
    price: 13,
    description: "Khung cảnh công viên",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Sông",
    category: "frame",
    image: "🌊",
    price: 15,
    description: "Khung cảnh sông",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Rừng",
    category: "frame",
    image: "🌲",
    price: 16,
    description: "Khung cảnh rừng",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Thành Phố",
    category: "frame",
    image: "🏙️",
    price: 18,
    description: "Khung cảnh thành phố",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Chợ",
    category: "frame",
    image: "🏪",
    price: 17,
    description: "Khung cảnh chợ",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Vườn",
    category: "frame",
    image: "🌻",
    price: 14,
    description: "Khung cảnh vườn",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Hoàng Hôn",
    category: "frame",
    image: "🌅",
    price: 19,
    description: "Khung cảnh hoàng hôn",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Bình Minh",
    category: "frame",
    image: "🌄",
    price: 19,
    description: "Khung cảnh bình minh",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Trăng",
    category: "frame",
    image: "🌙",
    price: 20,
    description: "Khung cảnh trăng",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Khung Sao",
    category: "frame",
    image: "⭐",
    price: 18,
    description: "Khung cảnh sao",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Đèn Lồng",
    category: "sticker",
    image: "🏮",
    price: 5,
    description: "Đèn lồng đỏ",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Diều Giấy",
    category: "sticker",
    image: "🪁",
    price: 10,
    description: "Diều giấy bay",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Mặt Nạ",
    category: "sticker",
    image: "🎭",
    price: 10,
    description: "Mặt nạ vui",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Trống",
    category: "sticker",
    image: "🥁",
    price: 15,
    description: "Trống đánh",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Kèn",
    category: "sticker",
    image: "🎺",
    price: 12,
    description: "Kèn thổi",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Đàn",
    category: "sticker",
    image: "🎸",
    price: 14,
    description: "Đàn ghi-ta",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Bóng Bay",
    category: "sticker",
    image: "🎈",
    price: 6,
    description: "Bóng bay đẹp",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Xe Đạp",
    category: "sticker",
    image: "🚲",
    price: 13,
    description: "Xe đạp đi chơi",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Máy Bay",
    category: "sticker",
    image: "✈️",
    price: 15,
    description: "Máy bay bay",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Tàu Thủy",
    category: "sticker",
    image: "🚢",
    price: 14,
    description: "Tàu thủy",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Xe Hơi",
    category: "sticker",
    image: "🚗",
    price: 12,
    description: "Xe hơi đẹp",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Búp Bê",
    category: "sticker",
    image: "🎎",
    price: 11,
    description: "Búp bê dễ thương",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Gấu Bông",
    category: "sticker",
    image: "🧸",
    price: 13,
    description: "Gấu bông mềm",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Xe Lửa",
    category: "sticker",
    image: "🚂",
    price: 14,
    description: "Xe lửa chạy",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Bánh Chưng",
    category: "sticker",
    image: "🍙",
    price: 8,
    description: "Bánh chưng Tết",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Bánh Dày",
    category: "sticker",
    image: "🍘",
    price: 8,
    description: "Bánh dày",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Hoa Đào",
    category: "sticker",
    image: "🌸",
    price: 7,
    description: "Hoa đào Tết",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Hoa Mai",
    category: "sticker",
    image: "🌺",
    price: 7,
    description: "Hoa mai vàng",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Cờ Tổ Quốc",
    category: "sticker",
    image: "🇻🇳",
    price: 10,
    description: "Cờ Tổ quốc",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Sao Vàng",
    category: "sticker",
    image: "⭐",
    price: 9,
    description: "Sao vàng năm cánh",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
  {
    name: "Bánh Xe",
    category: "sticker",
    image: "🎡",
    price: 12,
    description: "Bánh xe quay",
    unlockType: "coins",
    unlockCondition: null,
    downloadable: true,
    imageFile: null,
    downloadFile: null,
    isActive: true,
  },
];

async function main() {
  console.log('🌱 Seeding album items...');
  
  for (const item of albumItems) {
    await prisma.albumItem.upsert({
      where: { 
        // Use name + category as unique identifier
        id: '', // Will be created if not exists
      },
      update: item,
      create: item,
    });
  }
  
  console.log(`✅ Seeded ${albumItems.length} album items`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
